# This is a basic workflow to help you get started with Actions

name: Compiling Source Mod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Compiling_Source_Mod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #  1) Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Create clean plugins folder
        run: |
          mkdir -p build/addons/sourcemod/scripting/include
          mkdir -p build/addons/sourcemod/plugins
          mkdir -p build/addons/sourcemod/translations
          
      - name: Moving translations
        run: |
          echo "checking if folder exist or not when moving file"
          ls
          mv addons/sourcemod/translations/* build/addons/sourcemod/translations/
        
      - name: Download SourceMod
        run: |
            echo "Download und extract sourcemod",
            wget "http://www.sourcemod.net/latest.php?version=1.8&os=linux" -O sourcemod.tar.gz
            tar -xzf sourcemod.tar.gz
            
      - name: Setup Plugins Version and start compiling 
        run: |
          chmod +x addons/sourcemod/scripting/spcomp
          echo "Set plugins version",
          chmod +x setup.sh
          ./setup.sh
            
      - name: Move plugins files to their folder
        run: |
         echo "Move plugins files to their folder",
          mv addons/sourcemod/scripting/include/hexvips.inc build/addons/sourcemod/scripting/include,
          mv addons/sourcemod/scripting/hexvips.sp build/addons/sourcemod/scripting,
          mv addons/sourcemod/scripting/vipmenu.sp build/addons/sourcemod/scripting,
          mv addons/sourcemod/scripting/compiled/hexvips.smx build/addons/sourcemod/plugins.
          
      - name: Moving License and Compresssing License 
        run: |
         mv LICENSE build/
         cd build/ && zip -9rq HexVips.zip addons/ LICENSE && mv HexVips.zip ../.
       
      - name: Show Content
        run: |
            ls
            echo pwd

            
      - name: Build Done
        run: echo "Build done"
       
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.13
        with:
          tag_name: release
          files: HexVips.zip
       
       
         
     
      
      
